name: my_plugin_ios
description: An implementation for the iOS platform of the Flutter my_plugin plugin.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  my_plugin_platform_interface:
    path: ../my_plugin_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0

flutter:
  plugin:
    implements: my_plugin
    platforms:
      ios:
        pluginClass: MyPluginPlugin
